version: '3'

services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: fsimage
            POSTGRES_USER: miserable
            POSTGRES_PASSWORD: s0HpYEGR
        ports:
            - 5432:5432
        volumes:
            - ./fsimage/data:/var/lib/db
        deploy:
            placement:
                constraints: [node.role == manager]

    naming:
        image: thelawds/naming_node
        ports:
            - 8080:8080
        depends_on:
            - database
        deploy:
            replicas: 1
            restart-policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]

    storage:
        build: thelawds/naming_node
        ports:
            - 8080:8080
        depends_on:
            - naming
        deploy:
            replicas: 3
            restart-policy:
                condition: on-failure
            placement:
                constraints: [node.role == worker]
