spring:
  datasource:
    username: miserable
    password: s0HpYEGR
    url: jdbc:postgresql://database:5432/fsimage
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info