logging:
  level:
    root: info


server:
  port: 8081

application:
  nameNodeAddress: http://naming:8080
  baseDirectory: /home/ubuntu/sdfs

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1010MB